apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: Hook-Succeeded
spec:
  template:
    spec:
      containers:
        - name: postsync-job
          image: curlimages/curl:latest  # Use a lightweight curl image
          command: ["/bin/sh", "-c"]
          args:
            - >
              curl -X POST http://prometheus-service.shahzeb-test:9090/-/reload -v
      restartPolicy: Never  # Ensure the Job doesn't restart automatically