ruleFilesDirectory:
- alerts/standalone
- alerts/loki
- alerts/prometheus-rw1
namespace: shahzeb-test
alertConfigName: prometheus-rules
alert_timing_medium: 10m
alert_timing_slow: 15m
alert_timing_fast: 5m