groups:
- name: "PrometheusTest"
  rules:
  # This alert allows manually triggering an alert for testing purposes.
  # It can be triggered with the following command (creates a pod with a certain name that cannot be scheduled):
  # kubectl run busybox-prometheus-test --overrides='{ "spec": { "nodeSelector": { "SOMETHING": "WRONG" } } }' --image=busybox --restart=Never -- sh -c 'while true; do sleep 1000; done'
  # Delete afterwards with: kubectl delete pod busybox-prometheus-test

  - alert: PrometheusTest
    expr: sum by (namespace, pod, environment) (kube_pod_status_phase{pod="busybox-prometheus-test", phase=~"Pending|Unknown|Failed"}) > 0
    for: 1m
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: Test alert from Prometheus
      description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} in environment {{ $labels.environment }} has been in a non-ready state for longer than 15 minutes."
      action: "To stop this test alert, remove the pod listed in the description."
