groups:
- name: "KubernetesDevOps"
  rules:

  - alert: KubernetesPodNotHealthy
    expr: |
      (sum by (namespace, pod, phase) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0)
      * on(namespace, pod) group_left(reason) (kube_pod_status_reason > 0)
    for: ${alert_timing_medium}
    labels:
      severity: critical
      category: service
    annotations:
      summary: Kubernetes Pod not healthy
      description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in {{ $labels.phase }} state (reason: {{ $labels.reasons }}) for longer than 15 minutes."
      action: "Investigate and repair the affected workload, e.g. by restarting or rolling back."
