groups:
  - name: "Loki"
    rules:

    - alert: "LokiRequestErrors"
      expr: |
        (
            sum(rate(loki_request_duration_seconds_count{status_code=~"5.."}[2m])) by (kubernetes_pod, route)
          / sum(rate(loki_request_duration_seconds_count[2m])) by (kubernetes_pod, route)
        ) * 100 > 10
      for: ${alert_timing_fast}
      labels:
        severity: critical
        category: shared-services
      annotations:
        summary: Loki fails to handle requests
        description: |
          {{ $labels.kubernetes_pod }} handling {{ $labels.route }} is experiencing {{ printf "%.2f" $value }}% errors
        action: "Look at the logs of all Loki components to determine the issue."

    - alert: "LokiRequestPanics"
      expr: sum(increase(loki_panic_total[10m])) by (kubernetes_pod, route) > 0
      for: ${alert_timing_fast}
      labels:
        severity: critical
        category: shared-services
      annotations:
        summary: Loki panics while handling requests
        description: |
          {{ $labels.kubernetes_pod }} handling {{ $labels.route }} is experiencing a {{ printf "%.2f" $value }} increase of panics.
        action: "Look at the logs of all Loki components to determine the issue."

    - alert: "LokiRequestLatency"
      expr: |
        histogram_quantile(0.99,
          sum(rate(loki_request_duration_seconds_bucket{route!~"(?i).*tail.*"}[1m])) by (le, kubernetes_pod, route)
        ) > 1
      for: ${alert_timing_medium}
      labels:
        severity: critical
        category: shared-services
      annotations:
        summary: Loki shows increased request lantency
        description: |
          {{ $labels.kubernetes_pod }} handling {{ $labels.route }} is experiencing {{ printf "%.2f" $value }}s 99th percentile latency.
        action: "Check Loki's logs for hints of the issue, also look at CPU and network utilization of the affected container(s). Consider increasing resource limits, or reducing the workload."

    - alert: "LokiTooManyCompactorsRunning"
      expr: sum(loki_boltdb_shipper_compactor_running) by (kubernetes_namespace) > 1
      for: ${alert_timing_fast}
      labels:
        severity: warning
        category: shared-services
      annotations:
        summary: More than one Loki Compactor runs the same time
        description: |
          {{ printf "%.0f" $value }} Loki compactors are running for more than 5m. Only one compactor should run at a time.
        action: "Shut down all but one Loki Compactor instance."
