groups:
- name: thanos-store
  rules:

  - alert: ThanosStoreGrpcErrorRate
    expr: |
      (
          sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", kubernetes_service="thanos-storegateway"}[5m]))
        / sum by (job) (rate(grpc_server_started_total{kubernetes_service="thanos-storegateway"}[5m]))
      ) * 100 > 5
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Store is failing to handle qrpcd requests.
      description: "Thanos Store {{$labels.job}} is failing to handle {{$value | humanize}}% of requests."
      action: "Look at the Thanos Store logs, investigate and resolve the reason for the failed requests"

  - alert: ThanosStoreSeriesGateLatencyHigh
    expr: |
      histogram_quantile(0.99, sum by (job, le) (rate(thanos_bucket_store_series_gate_duration_seconds_bucket{kubernetes_service="thanos-storegateway"}[5m]))) > 2
      and
      sum by (job) (rate(thanos_bucket_store_series_gate_duration_seconds_count{kubernetes_service="thanos-storegateway"}[5m])) > 0
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Store has high latency for store series gate requests.
      description: "Thanos Store {{$labels.job}} has a 99th percentile latency of {{$value}} seconds for store series gate requests."
      action: "Look at the Thanos Store logs, investigate and resolve the reason for the slow requests. Check container resource usage, consider increasing resource limits."

  - alert: ThanosStoreBucketHighOperationFailures
    expr: |
      (
          sum by (job) (rate(thanos_objstore_bucket_operation_failures_total[5m]))
        / sum by (job) (rate(thanos_objstore_bucket_operations_total[5m]))
      ) * 100 > 5
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Store Bucket is failing to execute operations.
      description: "Thanos Store {{$labels.job}} Bucket is failing to execute {{$value | humanize}}% of operations."
      action: "Investigate the reason of the failed bucket operations, check the container logs. Likely reasons are connectivity to the storage backend, or problems with credentials or permissions."

  - alert: ThanosStoreObjstoreOperationLatencyHigh
    expr: |
      histogram_quantile(0.99, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket[5m]))) > 2
      and
      sum by (job) (rate(thanos_objstore_bucket_operation_duration_seconds_count[5m])) > 0
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Store is having high latency for bucket operations.
      description: "Thanos Store {{$labels.job}} Bucket has a 99th percentile latency of {{$value}} seconds for the bucket operations."
      action: "Investigate the reason for the high latency. The storage backend might be slow, the network might be congested, or the Thanos Store container might be low on resources."
