groups:
- name: thanos-component-absent
  rules:

  - alert: ThanosCompactIsDown
    expr: absent(up{job="kubernetes-service-endpoints", kubernetes_service="thanos-compactor"} == 1)
    for: ${alert_timing_medium}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: ThanosCompact has disappeared
      description: "ThanosCompact has disappeared. Prometheus target for the component cannot be discovered."
      action: "Investigate why the Thanos Compactor cannot be scraped by Prometheus. Either it is not running, or there is a connectivity issue."

  - alert: ThanosQueryIsDown
    expr: absent(up{job="kubernetes-service-endpoints", kubernetes_service="thanos-query"} == 1)
    for: ${alert_timing_medium}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: ThanosQuery has disappeared
      description: "ThanosQuery has disappeared. Prometheus target for the component cannot be discovered."
      action: "Investigate why the Thanos Query cannot be scraped by Prometheus. Either it is not running, or there is a connectivity issue."

  - alert: ThanosRuleIsDown
    expr: absent(up{job="kubernetes-service-endpoints", kubernetes_service="thanos-ruler"} == 1)
    for: ${alert_timing_medium}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: ThanosRule has disappeared
      description: "ThanosRule has disappeared. Prometheus target for the component cannot be discovered."
      action: "Investigate why the Thanos Ruler cannot be scraped by Prometheus. Either it is not running, or there is a connectivity issue."

  - alert: ThanosStoreIsDown
    expr: absent(up{job="kubernetes-service-endpoints", kubernetes_service="thanos-storegateway"} == 1)
    for: ${alert_timing_medium}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: ThanosStore has disappeared
      description: "ThanosStore has disappeared. Prometheus target for the component cannot be discovered."
      action: "Investigate why the Thanos Store cannot be scraped by Prometheus. Either it is not running, or there is a connectivity issue."

#  - alert: ThanosBucketReplicateIsDown
#    expr: absent(up{job="kubernetes-service-endpoints", kubernetes_service="thanos-bucket-replicate"} == 1)
#    for: ${alert_timing_medium}
#    labels:
#      severity: critical
#      category: shared-services
#    annotations:
#      summary: ThanosBucketReplicate has disappeared
#      description: "ThanosBucketReplicate has disappeared. Prometheus target for the component cannot be discovered."
#      action: "Investigate why the Thanos Bucket Replicate cannot be scraped by Prometheus. Either it is not running, or there is a connectivity issue."
#
#  - alert: ThanosReceiveIsDown
#    expr: absent(up{job="kubernetes-service-endpoints", kubernetes_service="thanos-receive"} == 1)
#    for: ${alert_timing_medium}
#    labels:
#      severity: critical
#      category: shared-services
#    annotations:
#      summary: ThanosReceive has disappeared
#      description: "ThanosReceive has disappeared. Prometheus target for the component cannot be discovered."
#      action: "Investigate why the Thanos Receiver cannot be scraped by Prometheus. Either it is not running, or there is a connectivity issue."
