groups:
- name: thanos-query
  rules:

  - alert: ThanosQueryHttpRequestQueryErrorRateHigh
    expr: |
      (
          sum by (instance) (rate(http_requests_total{code=~"5..", kubernetes_service="thanos-query", handler="query"}[5m]))
        / sum by (instance) (rate(http_requests_total{kubernetes_service="thanos-query", handler="query"}[5m]))
      ) * 100 > 5
    for: ${alert_timing_fast}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: Thanos Query is failing to handle requests.
      description: "Thanos Query is failing to handle {{printf \"%.2f\" $value}}% of 'query' requests."
      action: "Look at the Thanos Query logs, investigate and resolve the reason for the failed requests"

  - alert: ThanosQueryHttpRequestQueryRangeErrorRateHigh
    expr: |
      (
          sum by (instance) (rate(http_requests_total{code=~"5..", kubernetes_service="thanos-query", handler="query_range"}[5m]))
        / sum by (instance) (rate(http_requests_total{kubernetes_service="thanos-query", handler="query_range"}[5m]))
      ) * 100 > 5
    for: ${alert_timing_fast}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: Thanos Query is failing to handle requests.
      description: "Thanos Query is failing to handle {{printf \"%.2f\" $value}}% of 'query_range' requests."
      action: "Look at the Thanos Query logs, investigate and resolve the reason for the failed requests"

  - alert: ThanosQueryGrpcServerErrorRate
    expr: |
      (
          sum by (instance) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", kubernetes_service="thanos-query"}[5m]))
        / sum by (instance) (rate(grpc_server_started_total{kubernetes_service="thanos-query"}[5m]))
      * 100 > 5
      )
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Query is failing to handle GRPC requests.
      description: "Thanos Query is failing to handle {{printf \"%.2f\" $value}}% of requests."
      action: "Look at the Thanos Query logs, investigate and resolve the reason for the failed requests"

  - alert: ThanosQueryGrpcClientErrorRate
    expr: |
      (
          sum by (instance) (rate(grpc_client_handled_total{grpc_code!="OK", kubernetes_service="thanos-query"}[5m]))
        / sum by (instance) (rate(grpc_client_started_total{kubernetes_service="thanos-query"}[5m]))
      ) * 100 > 5
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Query is failing to send requests.
      description: "Thanos Query is failing to send {{printf \"%.2f\" $value}}% of requests."
      action: "Look at the Thanos Query logs, investigate and resolve the reason for the failed requests"

  - alert: ThanosQueryHighDNSFailures
    expr: |
      (
          sum by (instance) (rate(thanos_query_store_apis_dns_failures_total[5m]))
        / sum by (instance) (rate(thanos_query_store_apis_dns_lookups_total[5m]))
      ) * 100 > 1
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Query is having high number of DNS failures.
      description: "Thanos Query has {{printf \"%.2f\" $value}}% of failing DNS queries for store endpoints."
      action: "Look at the Thanos Query logs and status page, find the domains that cannot be resolved. Investigate DNS resolution and check whether the respective Kubernetes service resources have correct endpoints associated."

  - alert: ThanosQueryInstantLatencyHigh
    expr: |
      histogram_quantile(0.99, sum by (instance, le) (rate(http_request_duration_seconds_bucket{kubernetes_service="thanos-query", handler="query"}[5m]))) > 40
      and
      sum by (instance) (rate(http_request_duration_seconds_bucket{kubernetes_service="thanos-query", handler="query"}[5m])) > 0
    for: ${alert_timing_fast}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: Thanos Query has high latency for queries.
      description: "Thanos Query has a 99th percentile latency of {{printf \"%.2f\" $value}} seconds for instant queries."
      action: "Look at the Thanos Query logs, investigate and resolve the reason for the slow requests. Check container resource usage, consider increasing resource limits."

  - alert: ThanosQueryRangeLatencyHigh
    expr: |
      histogram_quantile(0.99, sum by (instance, le) (rate(http_request_duration_seconds_bucket{kubernetes_service="thanos-query", handler="query_range"}[5m]))) > 90
      and
      sum by (instance) (rate(http_request_duration_seconds_count{kubernetes_service="thanos-query", handler="query_range"}[5m])) > 0
    for: ${alert_timing_fast}
    labels:
      severity: critical
      category: shared-services
    annotations:
      summary: Thanos Query has high latency for queries.
      description: "Thanos Query has a 99th percentile latency of {{printf \"%.2f\" $value}} seconds for range queries."
      action: "Look at the Thanos Query logs, investigate and resolve the reason for the slow requests. Check container resource usage, consider increasing resource limits."
