groups:
- name: thanos-compact
  rules:

  - alert: ThanosCompactMultipleRunning
    expr: sum by (instance) (up{kubernetes_service="thanos-compactor"}) > 1
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Compact has multiple instances running
      description: "No more than one Thanos Compact instance should be running at once. There are {{$value}} instances running."
      action: "Shut down all but one Thanos Compact instance."

  # Hint for resolving Thanos error "pre compaction overlap check: overlaps found while gathering blocks"
  # In the error message, look for block ids (ulid: ...). Go to the storage account ptfiacstathanosweu1 and manually delete all contents in the block folders.
  # For every overlap, only one of the conflicting blocks has to be deleted, the other one an be left intact.
  # To avoid this, ensure globally unique "external_labels" in every Prometheus instance in every environment!
  - alert: ThanosCompactHalted
    expr: thanos_compact_halted == 1
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Compact has failed to run and is now halted
      description: "Thanos Compact has failed to run and now is halted. This can result in high storage consumption and low query performance in the long run."
      action: "Investigate the reason why Thanos Compact failed, check the container logs. Resolve the issue and restart the container. "

  - alert: ThanosCompactHighCompactionFailures
    expr: |
      (
          sum by (instance) (rate(thanos_compact_group_compactions_failures_total[24h]))
        / sum by (instance) (rate(thanos_compact_group_compactions_total[24h]))
      ) * 100 > 5
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Compact is failing to execute compactions
      description: "Thanos Compact is failing to execute {{printf \"%.2f\" $value}}% of compactions."
      action: "Investigate the reason of the failed compaction runs, check the container logs. Likely reasons are connectivity to the storage backend, or problems with credentials or permissions."

  - alert: ThanosCompactBucketHighOperationFailures
    expr: |
      (
          sum by (instance) (rate(thanos_objstore_bucket_operation_failures_total[5m]))
        / sum by (instance) (rate(thanos_objstore_bucket_operations_total[5m]))
      ) * 100 > 5
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Compact Bucket is having a high number of operation failures
      description: "Thanos Compact Bucket is failing to execute {{printf \"%.2f\" $value}}% of operations."
      action: "Investigate the reason of the failed bucket operations, check the container logs. Likely reasons are connectivity to the storage backend, or problems with credentials or permissions."

  - alert: ThanosCompactHasNotRun
    expr: (time() - max by (job) (max_over_time(thanos_objstore_bucket_last_successful_upload_time[24h]))) / 60 / 60 > 24
    for: ${alert_timing_fast}
    labels:
      severity: warning
      category: shared-services
    annotations:
      summary: Thanos Compact has not uploaded anything for last 24 hours
      description: "Thanos Compact has not uploaded anything for 24 hours."
      action: "Investigate the reason why Thanos is not doing compactions, check the container logs and the Thanos Compact configuration."
