apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alertConfigName }}
  namespace: {{ .Values.namespace }}
data:
  {{- $medium := .Values.alert_timing_medium }}
  {{- $slow := .Values.alert_timing_slow }}
  {{- $fast := .Values.alert_timing_fast }}

  {{- range $directory := .Values.ruleFilesDirectory  }}
    {{- $files := $.Files.Glob (printf "%s/*.yaml" $directory)  }}
    {{- range $path, $file := $files }}
      {{ $base := base $path }}
      {{ $base }}: |
        {{ $file | toString | replace "${alert_timing_medium}" $medium | replace "${alert_timing_slow}" $slow | replace "${alert_timing_fast}" $fast | nindent 8 }}
    {{- end }}
  {{- end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: Hook-Succeeded
spec:
  template:
    spec:
      containers:
        - name: postsync-job-success
          image: ubuntu
          command: 
            - /bin/bash
            - -c
            - |
              apt update -y
              echo "*******************************************************************************************************************************************"
              apt upgrade -y
              echo "*******************************************************************************************************************************************"
              apt install curl -y
              echo "*******************************************************************************************************************************************"
              curl --version
              echo "*******************************************************************************************************************************************"
              sleep 10
              curl --retry 3 --retry-delay 5 -X POST http://prometheus-service.shahzeb-test.svc:9090/-/reload -v
          
      restartPolicy: Never  # Ensure the Job doesn't restart automatically