apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alertConfigName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  {{- $medium := .Values.alert_timing_medium }}
  {{- $slow := .Values.alert_timing_slow }}
  {{- $fast := .Values.alert_timing_fast }}

  {{- range $directory := .Values.ruleFilesDirectory  }}
    {{- $files := $.Files.Glob (printf "%s/*.yaml" $directory)  }}
    {{- range $path, $file := $files }}
      {{ $base := base $path }}
      {{ $base }}: |
        {{ $file | toString | replace "${alert_timing_medium}" $medium | replace "${alert_timing_slow}" $slow | replace "${alert_timing_fast}" $fast | nindent 8 }}
    {{- end }}
  {{- end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-reload
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Job to reload Prometheus in sync wave 1
    amespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      name: prometheus-reload
    spec:
      containers:
        - name: curl
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for 10 seconds to ensure ConfigMap is applied..."
              sleep 10
              curl --retry 5 --retry-delay 10 -X POST http://prometheus-service.shahzeb-test.svc:9090/-/reload -v
      restartPolicy: Never