apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alertConfigName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  {{- $medium := .Values.alert_timing_medium }}
  {{- $slow := .Values.alert_timing_slow }}
  {{- $fast := .Values.alert_timing_fast }}

  {{- range $directory := .Values.ruleFilesDirectory  }}
    {{- $files := $.Files.Glob (printf "%s/*.yaml" $directory)  }}
    {{- range $path, $file := $files }}
      {{ $base := base $path }}
      {{ $base }}: |
        {{ $file | toString | replace "${alert_timing_medium}" $medium | replace "${alert_timing_slow}" $slow | replace "${alert_timing_fast}" $fast | nindent 8 }}
    {{- end }}
  {{- end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              curl -X POST http://prometheus-service.shahzeb-test.svc:9090/-/reload -v
      restartPolicy: Never
---

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for 20 seconds to ensure ConfigMap is applied..."
              sleep 20  # Optional delay
              curl -X POST http://prometheus-service.shahzeb-test.svc:9090/-/reload -v
      restartPolicy: Never